# Generated by Django 2.0.10 on 2019-01-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Enter your name', max_length=20)),
            ],
            options={
                'ordering': ['-Name'],
            },
        ),
    ]
