# Generated by Django 2.0.10 on 2019-01-16 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesht', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ename',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
