# Generated by Django 2.0.10 on 2019-01-16 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timesht', '0004_auto_20190116_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ename',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 16, 10, 5, 10, 114345, tzinfo=utc)),
        ),
    ]
